packages:
  - "core"
  - "web"
  - "packages/*"

catalog:
  "@effect/platform": ^0.69.25
  "@effect/platform-node": "^0.64.27"
  "@effect/sql": "^0.20.8"
  "@effect/sql-pg": "^0.21.8"
  "@effect/experimenta": "^0.32.9"
  effect: ^3.10.16
  typescript: ^5.7.2
  vitest: ^1.6.0
  prettier: ^3.2.5
  prettier-plugin-tailwindcss: ^0.5.14
  autoprefixer: ^10.4.20
  postcss: ^8.4.47
  tailwindcss: ^3.4.15
  react: ^18.3.1
  react-dom: ^18.3.1
