packages:
  - "domain"
  - "core"
  - "web"
  - "packages/*"

catalog:
  "@effect/platform": "0.70.6"
  "@effect/platform-node": "0.65.6"
  "@effect/sql": "^0.22.6"
  "@effect/sql-pg": "^0.23.6"
  "@effect/experimental": "^0.32.9"
  "@effect/vitest": "^0.14.4"
  effect: ^3.11.4
  typescript: ^5.7.2
  prettier: ^3.2.5
  prettier-plugin-tailwindcss: ^0.5.14
  autoprefixer: ^10.4.20
  postcss: ^8.4.47
  tailwindcss: ^3.4.15
  react: ^18.3.1
  react-dom: ^18.3.1
  vite: ^5.4.10
  vite-tsconfig-paths: ^5.0.1
  vitest: ^2.0.5
